//! 构建期生成「扩展 JS 内嵌表」。
//!
//! 背景（缺陷：release 产物在非构建机不可用）：
//! deno_* 各 crate 用 `deno_core::extension!(..., lazy_loaded_js = ["26_fetch.js"])`
//! 声明扩展 JS。deno_core 0.411 的 `include_js_files!` 系列宏一律走 `mode=loaded`，
//! 产物是 `ExtensionFileSource::loaded_during_snapshot(spec, concat!(
//! env!("CARGO_MANIFEST_DIR"), ...))`——即把**构建机绝对路径**烧进二进制；未启用
//! startup snapshot 时，运行期 `ExtensionFileSource::load()` 会 `fs::read_to_string`
//! 该路径，于是在非构建机上 ENOENT（deno_core 的
//! "Failed to initialize a JsRuntime: No such file or directory"）。
//!
//! 这里把依赖 crate 的扩展 JS 在编译期 `include_str!` 进二进制，运行期由
//! `bridge::embedded_js::patch_fs_loaded_sources` 覆写为 `Computed` 源，彻底消除对
//! 构建机路径的依赖。deno_core 升级后若文件名/版本变化，本脚本会 fail-fast（找不到
//! 目录/无 .js/specifier 重复），不会静默发出坏产物。

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// 由 `bridge::ws_client_extensions` 注册、且以 `dir` / `lazy_loaded_*` 声明扩展 JS 的
/// 依赖 crate；与根 `Cargo.toml` 的 deno_* 依赖保持一致。
const CRATES: [&str; 5] = [
    "deno_web",
    "deno_fetch",
    "deno_net",
    "deno_websocket",
    "deno_webidl",
];

fn main() {
    println!("cargo:rerun-if-changed=Cargo.lock");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let cargo_home = env::var_os("CARGO_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| home_dir().join(".cargo"));
    let lock = fs::read_to_string(manifest_dir.join("Cargo.lock")).expect("read Cargo.lock");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for krate in CRATES {
        let version = lock_version(&lock, krate)
            .unwrap_or_else(|| panic!("Cargo.lock 中找不到 `{krate}` 的版本"));
        let dir = find_crate_dir(&manifest_dir, &cargo_home, krate, &version).unwrap_or_else(|| {
            panic!(
                "找不到 {krate}-{version} 的源码目录（检查 CARGO_HOME/registry/src 或 vendor/）；\
                 先执行 `cargo fetch`"
            )
        });
        let mut files: Vec<PathBuf> = fs::read_dir(&dir)
            .expect("read crate dir")
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "js"))
            .collect();
        files.sort();
        assert!(!files.is_empty(), "{krate}-{version} 下没有 .js 扩展源");
        for path in files {
            let base = path
                .file_name()
                .expect("js file has name")
                .to_string_lossy()
                .into_owned();
            println!("cargo:rerun-if-changed={}", path.display());
            entries.push((format!("ext:{krate}/{base}"), path));
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));
    for pair in entries.windows(2) {
        assert_ne!(pair[0].0, pair[1].0, "扩展 specifier 重复：{}", pair[0].0);
    }

    let mut generated = String::from(
        "// @generated by build.rs —— 勿手改。\n\
         /// `specifier -> 源码`：deno_* 依赖以绝对路径声明的扩展 JS，编译期随二进制内嵌。\n\
         pub static EMBEDDED_EXT_JS: &[(&str, &str)] = &[\n",
    );
    for (specifier, path) in &entries {
        // Windows 反斜杠 → 正斜杠：include_str! 两种都认，字面量用 `/` 更稳。
        let literal = path.display().to_string().replace('\\', "/");
        writeln!(generated, "    ({specifier:?}, include_str!({literal:?})),").expect("write");
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("embedded_ext_js.rs"), generated).expect("write generated table");
}

/// 从 Cargo.lock 取某 package 的版本（避免为构建脚本引入 toml 依赖）。
fn lock_version(lock: &str, name: &str) -> Option<String> {
    let needle = format!("name = \"{name}\"");
    let mut lines = lock.lines();
    while let Some(line) = lines.next() {
        if line.trim() != needle {
            continue;
        }
        for line in lines.by_ref() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix("version = \"") {
                return Some(rest.trim_end_matches('"').to_string());
            }
            if line.starts_with("[[package]]") {
                break;
            }
        }
    }
    None
}

/// 定位依赖 crate 的解包源码目录：优先 `vendor/`（cargo vendor），其次 CARGO_HOME 的
/// registry（registry 目录名带哈希，故遍历）。
fn find_crate_dir(
    manifest_dir: &Path,
    cargo_home: &Path,
    krate: &str,
    version: &str,
) -> Option<PathBuf> {
    let vendored = manifest_dir.join("vendor").join(krate);
    if vendored.is_dir() {
        return Some(vendored);
    }
    let registry_src = cargo_home.join("registry").join("src");
    let mut found = None;
    for entry in fs::read_dir(registry_src).ok()?.flatten() {
        let candidate = entry.path().join(format!("{krate}-{version}"));
        if candidate.is_dir() {
            found = Some(candidate);
        }
    }
    found
}

fn home_dir() -> PathBuf {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_default()
}
